### ISSUE TITLE
desktop app does not close

### ISSUE THREAD

**Issue by maheshrijal** [ente-io/ente#1210] opened 2024-03-26 05:35 UTC
### Steps to Replicate
1. Open ente-auth desktop app
2. Close the app
3. Expand the hidden icons, right click on ente-auth icon and click on exit
4. Notice that if the app is already minimized, nothing happens. If the app is in foreground it minizes

Expected behavior: app should close

### Version

2.0.46

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by vishnukvmd** [comment] 2024-03-26 11:09
Hey, minimizing to the system tray is the intended behavior.

> Expand the hidden icons, right click on ente-auth icon and click on exit

This is the right way to close the app. Please let us know if this isn't working!

**Comment by maheshrijal** [comment] 2024-03-26 11:23
It's not working. 

When the app is running in foreground and I click on exit, the app just minimizes instead of closing. Basically, the `Hide` & `Exit` button behave the same.

**Comment by maheshrijal** [comment] 2024-03-26 11:33
Here's a screen grab. This should make the issue more clear.

https://github.com/ente-io/ente/assets/62394512/6327615c-2ca9-428a-bc8e-e07aa683498a

**Comment by vishnukvmd** [comment] 2024-03-26 11:37
This is super helpful, thank you!

**Comment by prateekmedia** [comment] 2024-03-28 16:24
Should be fixed in latest version!

**Closed** 2024-03-28 21:16 UTC
Labels: --desktop, - auth
