### ISSUE TITLE
[⚠️CRITICAL ISSUE⚠️]  Cannot login to ente-auth Windows app

### ISSUE THREAD

**Issue by Ironfist69** [ente-io/ente#2234] opened 2024-06-20 16:57 UTC
### Description

![Screenshot 2024-06-20 150415](https://github.com/ente-io/ente/assets/70436487/49043c0c-cc2a-4a42-8346-4070017768ad)

**Edition**	Windows 11 Pro
**Version**	23H2
**Installed on**	‎19-‎Jun-‎24
**OS build**	22635.3785
**Experience**	Windows Feature Experience Pack 1000.22700.1023.0

### Version

v3.0.13

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment] 2024-06-21 03:37
Duplicate of https://github.com/ente-io/ente/issues/2178

**Closed by ua741** 2024-06-21 03:37 UTC
Labels: triage
