### ISSUE TITLE
Export Data Encrypted - keyboard input does not work

### ISSUE THREAD

**Issue by petardo1** [ente-io/ente#3896] opened 2024-10-31 20:53 UTC
### Description

Export Data Encrypted - keyboard input does not work. I can input password only by right click / paste.
Edit: putting on tray and back solves the problem.
It seams to be a getting focus problem.

### Version

4.0.3

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment] 2024-12-07 08:10
Dupe of https://github.com/ente-io/ente/issues/2262

**Closed by ua741** 2024-12-07 08:10 UTC
Labels: --desktop, - auth
