### ISSUE TITLE
Lots of metadata is lost when rotating a photo and resaving

### ISSUE THREAD

**Issue by sneak** [ente-io/ente#3211] opened 2024-09-10 10:13 UTC
### Description

I have some photos that were taken with iPhones that are not in the correct orientation.   When using the edit tool to rotate the photo to the correct orientation, and resaving the photo to Ente, much of the image metadata is lost: location, phone make and model, etc.

### Version

v1.7.4

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - macOS

**Comment by ua741** [comment] 2024-09-17 03:47
Duplicate of https://github.com/ente-io/ente/issues/576

**Closed by ua741** 2024-09-17 03:47 UTC
Labels: triage
