### ISSUE TITLE
Ente desktop app won’t accept password

### ISSUE THREAD

**Issue by ajsteele** [ente-io/ente#1891] opened 2024-05-27 14:19 UTC
### Description

I just reinstalled the Ente app (Windows 10, installed with ente-1.6.63-x64.exe) and, when I try to sign in, it tells me my password is incorrect. The password works on the web app (in Firefox) and I’m copy/pasting from my password manager so it’s not a typing issue!

### Version

1.6.63

### What product are you using?

Ente Photos

### What platform are you using?

Windows 10

**Comment by ajsteele** [comment] 2024-05-27 14:36
Thanks for the rapid reply! I checked this too (also copy/pasted), and just did it once more to make sure. The email is definitely correct!

**Comment by mnvr** [comment] 2024-05-27 14:39
Hmm, weird. Could you send over your logs to support@ente.io, we can see if we spot anything there. Thanks. Also, if you could wait for a day or so, we also have a new version of the app coming out. While there isn't specifically a fix or any known issue around this password thing, maybe the shiny new version repels the cosmic rays.

**Comment by ajsteele** [comment] 2024-05-27 15:01
It is very odd!

I'll send over the logs if I still can't log in with the new version. Thanks!

**Comment by ajsteele** [comment] 2024-05-29 10:01
I just installed 1.7.0 and unfortunately the same problem recurs. Here’s a copy of the whole error log (clean install and one attempt to log in):

```
[2024-05-29T11:56:44+02:00] [main] [info] Starting ente-photos-desktop 1.7.0
[2024-05-29T11:56:44+02:00] [main] [info] Running on {
  platform: 'win32',
  osRelease: '10.0.19045',
  systemVersion: '10.0.19045'
}
[2024-05-29T11:56:45+02:00] Checking for update
[2024-05-29T11:56:45+02:00] Generated new staging user ID: 6faffd77-2986-5588-b89a-0cd3f9af8b4a
[2024-05-29T11:56:45+02:00] [rndr] [info] Opening Ml DB
[2024-05-29T11:56:45+02:00] [rndr] [info] Previous ML database v0 had ML search disabled
[2024-05-29T11:56:45+02:00] [rndr] [info] Starting ente-photos-web git f66ac40 uid 0
[2024-05-29T11:56:45+02:00] [rndr] [info] ML DB upgraded from version 0 to version 4
[2024-05-29T11:56:46+02:00] Update for version 1.7.0 is not available (latest version: 1.7.0, downgrade is disallowed).
[2024-05-29T11:57:08+02:00] [rndr] [error] HTTP Service Error - {"url":"https://api.ente.io/users/srp/verify-session","method":"post","xRequestId":"73625a64-e133-49ed-84db-0c280d424612","httpStatus":401}: ApiError: client error
ApiError: client error
    at ente://app/_next/static/chunks/pages/_app-2f9074c8ca1c80e2.js:123:244358
    at async ty.request (ente://app/_next/static/chunks/pages/_app-2f9074c8ca1c80e2.js:138:50250)
    at async a.request (ente://app/_next/static/chunks/pages/_app-2f9074c8ca1c80e2.js:123:243399)
    at async d (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:1044)
    at async S (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:3964)
    at async L (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:2028)
    at async Object.E [as callback] (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:13285)
    at async g (ente://app/_next/static/chunks/pages/index-75ed918ba4af85f8.js:1:11143)
[2024-05-29T11:57:08+02:00] [rndr] [error] verifySRPSession failed: ApiError: client error
ApiError: client error
    at ente://app/_next/static/chunks/pages/_app-2f9074c8ca1c80e2.js:123:244358
    at async ty.request (ente://app/_next/static/chunks/pages/_app-2f9074c8ca1c80e2.js:138:50250)
    at async a.request (ente://app/_next/static/chunks/pages/_app-2f9074c8ca1c80e2.js:123:243399)
    at async d (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:1044)
    at async S (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:3964)
    at async L (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:2028)
    at async Object.E [as callback] (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:13285)
    at async g (ente://app/_next/static/chunks/pages/index-75ed918ba4af85f8.js:1:11143)
[2024-05-29T11:57:08+02:00] [rndr] [error] srp verify failed: Error: incorrect password
Error: incorrect password
    at d (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:1262)
    at async S (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:3964)
    at async L (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:2028)
    at async Object.E [as callback] (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:13285)
    at async g (ente://app/_next/static/chunks/pages/index-75ed918ba4af85f8.js:1:11143)
[2024-05-29T11:57:08+02:00] [rndr] [error] getKeyAttributes failed: Error: incorrect password
Error: incorrect password
    at d (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:1262)
    at async S (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:3964)
    at async L (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:2028)
    at async Object.E [as callback] (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:13285)
    at async g (ente://app/_next/static/chunks/pages/index-75ed918ba4af85f8.js:1:11143)
[2024-05-29T11:57:08+02:00] [rndr] [error] failed to verify passphrase: Error: incorrect password
Error: incorrect password
    at d (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:1262)
    at async S (ente://app/_next/static/chunks/1263-9494872ff010d9a8.js:1:3964)
    at async L (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:2028)
    at async Object.E [as callback] (ente://app/_next/static/chunks/pages/credentials-e3c21c4f818d09ce.js:1:13285)
    at async g (ente://app/_next/static/chunks/pages/index-75ed918ba4af85f8.js:1:11143)
```

**Comment by mnvr** [comment] 2024-05-29 10:22
While I was hoping for it to work, it would've been puzzling if it started working after the update since as I mentioned, there haven't really been any issues fixed around this in the old version, and it'd already been working for months.

And thank you for posting the logs: while there are many errors in the log, those are just multiple places in the stack printing the same error, and this is all matching the logs that'd appear if the password were incorrect, it rules out anything else going wrong.

Since you've triple checked the password and email, and the same credentials are working say on the Ente web app, that means that somehow during the install / reinstall, something got corrupted in the local state that the desktop app keeps on the machine.

There are two things we can try now:

1. Please uninstall the app so that it clears its local %APPDATA%, then install it again.
2. If even that doesn't help, could you try on a different machine if possible.

**Comment by ajsteele** [comment] 2024-05-29 10:31
Thanks for the further troubleshooting steps but unfortunately neither worked… I uninstalled and manually checked that the ente folder in AppData/Roaming had been removed (which it had) and a clean install on my laptop (also Windows 10) has the same issue with an identical-looking log (same errors repeated the same number of times).

Sorry to be the bearer of annoying news!

**Comment by mnvr** [comment] 2024-05-29 10:54
One possibility that comes to mind is that you might have a very old SRP setup - when we'd initially rolled out SRP there was a bug that caused the password verification to fail in some cases. That bug was fixed but affected customers had to reset their passwords once to regenerate their SRP credentials (or we needed to manually bypass SRP once for them to go through the normal login flow without involving SRP).

Could you try this once:

1. Make **sure** you have your recovery key saved somewhere secure (I think you already have, just a reminder to double check the value from what is shown in your Firefox tab and the value you have saved).
2. On your Firefox session, change your password (you can reuse the same password again). This will cause the SRP attributes to be regenerated.
3. Then please try logging into the desktop app again.

**Comment by ajsteele** [comment] 2024-05-29 11:52
Thanks for the troubleshooting tips.

I tried this and it seems to have worked for Ente Photos—my password is accepted and it then asks me to input a two-factor authentication code. Unfortunately, when I try to log into Ente Auth to get one, my new password doesn't work, and my old password allows me to log in but shows me an empty account with no two-factor authentication codes set up.

Does this take some time to propagate, or has this process somehow caused me to lose all my Ente Auth data?

**Comment by ua741** [comment] 2024-05-29 12:17
> **my new password doesn't work, and my old password allows me to log in**

When you close a tab and open it again, the app asks you for the password to decrypt data from local storage. This data is encrypted with the old password, which is why using the old password allows you to move past that screen. We acknowledge that this creates confusion after changing the password. We will discuss it internally and come up with a better UX.

> shows me an empty account with no two-factor authentication codes set up.

There seems to be a bug. After changing the password, we invalidated old sessions. The web app should have shown you a prompt and asked you to sign in again. We will look into it.

> Does this take some time to propagate, or has this process somehow caused me to lose all my Ente Auth data?

The change happens immediately, and your Ente Auth data should be safe. 

Please use a different browser or the mobile app to log in to the Ente Auth app. If you have two-factor authentication enabled and your Ente two-factor code is [saved inside Ente Auth,](https://help.ente.io/auth/faq/enteception/) please use the recovery key to disable the second factor.

**Comment by ajsteele** [comment] 2024-05-29 12:26
That’s definitely confusing! And a little unnerving that it’s then empty. The behaviour on the mobile app was that it allowed me to sign in with biometrics and then was also empty.

I managed to sign out and in again on browser and got it working again with the recovery key—but upon trying to log out of the mobile app and I get a generic error message (‘It looks like something went wrong.’) I assume I can uninstall and reinstall to get around this? But it’s a very inconvenient and unnerving workflow if this is the normal behaviour on a password change!

**Comment by ua741** [comment] 2024-05-29 12:40
Agree with the feedback. I am sorry for creating unnecessary panic.

On the mobile app, once we detect that the token is invalid, we automatically wipe out all synced secrets from the local storage. After that, the app should display a dialog saying that you have been signed out and to please log in. There seems to be a regression here as well.

Thank you for your patience with us and for helping to identify these issues. We will check the behavior across apps and fix them.

**Comment by mnvr** [comment] 2024-06-28 07:49
Both the issues have now been fixed:

- Web and desktop both will do a pre-flight check on the enter password screen to see if the password was changed elsewhere, and if so, will reload itself so that the new creds can be used (https://github.com/ente-io/ente/pull/2230)

- Auth will invalidate existing sessions if the user chooses the option to log out of other devices (https://github.com/ente-io/ente/pull/1922)

For web the changes are already deployed. For desktop, they're already in the nightly build, and will also go out in the next release, 1.7.2 (est. end of next week).

I'll close this issue now. @ajsteele Thank you for your patience with us.

**Closed by mnvr** 2024-06-28 07:49 UTC
Labels: --desktop, - photos

**Comment by ajsteele** [comment] 2024-07-01 10:59
Thanks, glad I could help get this identified and fixed!

**Comment by Rising-Galaxy** [comment] 2024-08-31 16:01
Why tell me the password is incorrect right after I just registered?
