### ISSUE TITLE
[Auth] How It Works Button Broken

### ISSUE THREAD

**Issue by Damariobros** [ente-io/ente#3544] opened 2024-10-01 06:34 UTC
### Description

The "How it Works" button in the password change menu is broken and gives an error. The architecture page fails to display.
![image](https://github.com/user-attachments/assets/48fe1cfa-ab7f-449d-89b2-0f2c131207bf)

### Version

v4.0.2

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment] 2024-12-12 09:52
Duplicate of https://github.com/ente-io/ente/issues/2852

**Closed by ua741** 2024-12-12 09:52 UTC
Labels: - auth
