### ISSUE TITLE
The web app, as of 4th of May 2024, 18:18 GMT+1 (Berlin), generates incorrect TOTP codes and has incorrect timing.

### ISSUE THREAD

**Issue by TGRush** [ente-io/ente#1613] opened 2024-05-04 16:21 UTC
### Description

The codes that are generated on the ente.io/auth webapp are *false*. They do not work when copy-pasted or inputted manually into anything. Additionally, their time differs from the *correct* values that are shown to me in the mobile app

I've made sure to try in a clean Firefox 125.x installation, entirely stock.

### Version

N/A

### What product are you using?

Ente Auth

### What platform are you using?

Web - Firefox

**Comment by mnvr** [comment] 2024-05-06 15:38
The time on your computer seems to be off. I cannot reproduce this issue either. Please confirm that the time on your computer (where you are running your browser) is the same as the time on your mobile (where you're running the app).

If the time on your machine is incorrect, then these TOTP ("time based one-time passwords") will be incorrect.

**Comment by TGRush** [comment] 2024-05-07 18:14
They are both running with that timezone set, I've made sure to check that beforehand.

**Comment by mnvr** [comment] 2024-05-08 03:54
It could be some setting you've enabled in Firefox which is preventing it from getting the correct time. For example, here is someone who was not getting the correct time in Firefox after enabling `privacy.resistFingerprinting`.

**Comment by mnvr** [comment] 2024-05-08 03:54
The link: https://support.mozilla.org/en-US/questions/1351493

**Comment by TGRush** [comment] 2024-05-10 17:53
> It could be some setting you've enabled in Firefox which is preventing it from getting the correct time. For example, here is someone who was not getting the correct time in Firefox after enabling `privacy.resistFingerprinting`.

Oh that was it. Thank you! I didn't know it messed with timezones too

**Comment by mnvr** [comment] 2024-05-11 02:24
Great! Thanks for checking.

**Closed by mnvr** 2024-05-11 02:24 UTC
Labels: needs more info, --web, - auth
