### ISSUE TITLE
4.1.0 update thinks codes database is empty. (Logging out and in again 'fixes' it)

### ISSUE THREAD

**Issue by LWGShane** [ente-io/ente#4190] opened 2024-11-26 14:04 UTC
### Description

Time for me to find another weird bug in apps I use, this time it's Ente Auth:

I updated my Windows app to 4.1.0 and upon launching it, the app acted like it was a brand new account with no codes. 

However, I logged out and then logged back in and that appears to have fixed it.

### Version

4.1.0

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by ua741** [comment] 2024-11-28 06:24
There was an migration issue that affect folks who were using beta build. Closing it as duplicate of [this issue](https://github.com/ente-io/ente/issues/4101#issuecomment-2494789267).

**Closed by ua741** 2024-11-28 06:24 UTC
Labels: triage
