### ISSUE TITLE
Can not install Ente Auth on Ubuntu LTS 24.04

### ISSUE THREAD

**Issue by Themanhdh** [ente-io/ente#3236] opened 2024-09-12 03:10 UTC
### Description

I got this issue when install Ente Auth. How to fix this?
![image](https://github.com/user-attachments/assets/618138fd-cc06-4aa2-a5ba-b3a04f515a50)

**Comment by ikeman2003** [comment] 2024-09-12 05:41
Same issue on Linux Mint 22 "Wilma".

Makes sense since it's based on Ubuntu 24.04. 

Also going to mention that the app was already installed for me originally but stopped working and gave the error when I attempt to reinstall.

![image](https://github.com/user-attachments/assets/398755a4-528e-4c8e-94d4-119749c0830c)

**Comment by tur1ngb0x** [comment] 2024-09-12 05:56
Duplicate of https://github.com/ente-io/ente/issues/3106

**Closed** 2024-09-18 14:43 UTC
Labels: triage
