### ISSUE TITLE
After some months of usage Ente opened without any keys running... 

### ISSUE THREAD

**Issue by mpuz** [ente-io/ente#4094] opened 2024-11-19 09:39 UTC
### Description

All data has disappeared...
![Screenshot from 2024-11-19 12-34-40](https://github.com/user-attachments/assets/0cbde963-2157-4709-b0fa-a35cc49c5f0b)

**Comment by LeeGDavis** [comment] 2024-11-19 16:10
I just ran into this same issue after upgrading to 4.1.0 from the beta and on Win 11.   Thankfully logging out and back in works around this.

**Comment by ua741** [comment] 2024-11-28 06:24
There was an migration issue that affect folks who were using beta build. Closing it as duplicate of [this issue](https://github.com/ente-io/ente/issues/4101#issuecomment-2494789267).

**Closed by ua741** 2024-11-28 06:24 UTC
Labels: triage
