### ISSUE TITLE
[AUTH] ios device can't login to Ente-Auth when 2FA enable + passkey enable in PC

### ISSUE THREAD

**Issue by mapxn** [ente-io/ente#4074] opened 2024-11-18 08:17 UTC
### Description

I downloaded Ente-Auth on my iPhone, and trying login to Ente-Auth using my account + password, which automatically redirected me to the browser for passkey verification. Of course, my phone couldn't verify the passkey because my passkey was added to the computer. There is no place to enter the OTP, which is very unreasonable.

### Version

v4.0.2

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - iOS, Web - Chrome

**Comment by mapxn** [comment] 2024-11-18 08:21
When users enable 2FA, they should be given the choice of using passkey or OTP when logging in. Instead of forcing users to use passkey.

**Comment by ua741** [comment] 2024-11-29 08:56
Duplicate of https://github.com/ente-io/ente/discussions/2416

**Closed by ua741** 2024-11-29 08:56 UTC
Labels: triage
