### ISSUE TITLE
[Auth][Windows] Can't login to desktop app

### ISSUE THREAD

**Issue by gokulkgm** [ente-io/ente#2178] opened 2024-06-17 12:52 UTC
### Description

Hello Team,

I installed Auth 3.0.12 on my desktop and when trying to login, getting the below error.

![image](https://github.com/ente-io/ente/assets/8915158/5febba77-1528-48b4-b106-f69822d2a7ca)

I've email verification turned on for login.

Could you please let know how to resolve this issue?

### Version

3.0.12

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Windows

**Comment by lecuong04** [comment] 2024-06-19 16:17
Are you using Windows 11 IoT Enterprise LTSC?
I have the same problem as you

**Comment by Ironfist69** [comment] 2024-06-20 09:37
![Screenshot 2024-06-20 150415](https://github.com/ente-io/ente/assets/70436487/45a9c5e9-752f-4bd0-b0bd-129c210398da)

### Platform

Edition	Windows 11 Pro
Version	23H2
Installed on	‎19-‎Jun-‎24
OS build	22635.3785
Experience	Windows Feature Experience Pack 1000.22700.1023.0

**Comment by Ironfist69** [comment] 2024-06-21 03:52
Any update on this issue ? Or do I need to switch to different TOTP app ??

**Comment by Juanmi18** [comment] 2024-06-22 08:48
Hi! First one, congratulations for Ente Auth os a 10/10 app for me.

About login un Windows, the same problem here.

Last versión with allí updates on Windows 11 IoT LTSC

Thanks!

**Comment by gokulkgm** [comment] 2024-06-22 10:36
@ua741 I'm getting this issue in clean installed Win 11 24H2 builds also.

I've attached the log [2024-6-22.txt](https://github.com/user-attachments/files/15936208/2024-6-22.txt)

Is there any workaround?

Edition	Windows 11 Home Single Language
Version	24H2
Installed on	‎21-‎06-‎2024
OS build	26100.994
Experience	Windows Feature Experience Pack 1000.26100.6.0

**Comment by ua741** [comment] 2024-06-22 11:47
> @ua741 I'm getting this issue in clean installed Win 11 24H2 builds also.
> 
> I've attached the log [2024-6-22.txt](https://github.com/user-attachments/files/15936208/2024-6-22.txt)
> 

Thank you for the logs. Unfortunately, we are unable to re-produce this issue on our test Windows machine.
I have tried a potential fix for this particular SSL handshake issue. It would be great if you can install the [beta version](https://github.com/ente-io/ente/releases/tag/auth-v3.0.15-beta.2), and let us know if it works or not.

**Comment by gokulkgm** [comment] 2024-06-22 12:11
Thanks @ua741 , the beta version works!

**Comment by Juanmi18** [comment] 2024-06-22 16:35
> > @ua741 I'm getting this issue in clean installed Win 11 24H2 builds also.
> > I've attached the log [2024-6-22.txt](https://github.com/user-attachments/files/15936208/2024-6-22.txt)
> 
> Thank you for the logs. Unfortunately, we are unable to re-produce this issue on our test Windows machine. I have tried a potential fix for this particular SSL handshake issue. It would be great if you can install the [beta version](https://github.com/ente-io/ente/releases/tag/auth-v3.0.15-beta.2), and let us know if it works or not.

In my case, don't work, the same issue.

My system:
Microsoft Windows 11 IoT Enterprise LTSC (10.0.26100 N/D Compilación 26100)

[2024-6-22.txt](https://github.com/user-attachments/files/15937432/2024-6-22.txt)

**Comment by ua741** [comment] 2024-06-23 06:36
@Juanmi18 Can you please upgrade to v3.0.17. In that, I have added additional logs to debug this issue. Thanks.

**Comment by Juanmi18** [comment] 2024-06-23 17:30
> @Juanmi18 Can you please upgrade to v3.0.17. In that, I have added additional logs to debug this issue. Thanks.

@ua741 I attach the logs. 

Thanks ;-)
[2024-6-23.txt](https://github.com/user-attachments/files/15945470/2024-6-23.txt)

**Comment by gokulkgm** [comment] 2024-06-23 18:44
@Juanmi18, do you install the beta updates over the existing installation, or do you uninstall the current version before installing the beta? 

I've found that uninstalling the current version and then installing the beta works for me.

**Comment by Juanmi18** [comment] 2024-06-23 19:17
I uninstalled the beta versión and install the new version.

The first one (3.13) I installed vía chocolatey and the beta versión and
3.17 vía installer (previously uninstalling)

Can I do something more?

Thanks ;)

**Comment by Blazetron9k** [comment] 2024-06-24 20:57
Even on 3.17 Via Installer, still getting errors.

[2024-6-24.txt](https://github.com/user-attachments/files/15961110/2024-6-24.txt)

On Windows 11 Pro, 
Version 23H2
Installed on ‎24-‎06-‎2024
OS build 22631.2715
Experience Windows Feature Experience Pack 1000.22677.1000.0

**Comment by Blazetron9k** [comment] 2024-06-24 22:13
> Even on 3.17 Via Installer, still getting errors.
> 
> [2024-6-24.txt](https://github.com/user-attachments/files/15961110/2024-6-24.txt)
> 
> On Windows 11 Pro, Version 23H2 Installed on ‎24-‎06-‎2024 OS build 22631.2715 Experience Windows Feature Experience Pack 1000.22677.1000.0

Nevermind, Fixed Itself! Probably just a issue with windows being setup + it being a early system.

**Comment by Juanmi18** [comment] 2024-06-25 06:54
For me the issue isn't fixed, still getting errors in two installations...

I Installed Windows 11 LTSC with this help: https://massgrave.dev/windows_ltsc_links 

If @ua741 want's reproduce the problem in his machine.

Thnaks in advance ;-)

**Comment by ua741** [comment] 2024-06-25 07:38
@Juanmi18 
Can you please check if this build fixes the issue for you https://github.com/ente-io/ente/releases/tag/auth-v3.0.18-beta.1

**Comment by Juanmi18** [comment] 2024-06-25 08:11
> @Juanmi18 Can you please check if this build fixes the issue for you https://github.com/ente-io/ente/releases/tag/auth-v3.0.18-beta.1

Don't work :-(

I attach the new logs.

[2024-6-25.txt](https://github.com/user-attachments/files/15967182/2024-6-25.txt)

**Comment by LabeebQa** [comment] 2024-07-01 14:56
Hi There,

I am also experiencing the same issue on a newly activated win11 machine...

`[_LoginPageState] [SEVERE] [2024-07-01 20:20:21.669339] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-07-01 20:20:21.962131] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [_LoginPageState] [SEVERE] [2024-07-01 20:20:48.146870] Error getting SRP attributes
⤷ type: DioException
⤷ error: DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
 [UserService] [INFO] [2024-07-01 20:20:48.444249] DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
`

 I suspect there's something wrong with the SSL certificate validation config


Edition	Windows 11 Pro
Version	23H2
Installed on	‎6/‎28/‎2024
OS build	22631.3810
Experience	Windows Feature Experience Pack 1000.22700.1020.0

**Comment by prateekmedia** [comment] 2024-07-23 08:31
Please try `auth-v3.0.18-beta.2` as it tries to fix this error.

**Comment by je-sam** [comment] 2024-08-04 21:50
Hello,
I have try auth-v3.0.18-beta.2 unfortunately I have the same error, 

![image](https://github.com/user-attachments/assets/1cbe3a42-8c41-4602-b19b-51bd481effdb)

Windows 11 Pro
23H2
22631.3880
Windows Feature Experience Pack 1000.22700.1020.0

Thank you for your work
Je

**Closed** 2024-08-04 22:32 UTC
Labels: --desktop, - auth

**Comment by marklesterb28** [comment] 2024-08-15 18:10
> Hello, I have try auth-v3.0.18-beta.2 unfortunately I have the same error,
> 
> ![image](https://private-user-images.githubusercontent.com/177486770/354931086-1cbe3a42-8c41-4602-b19b-51bd481effdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDU2NzEsIm5iZiI6MTcyMzc0NTM3MSwicGF0aCI6Ii8xNzc0ODY3NzAvMzU0OTMxMDg2LTFjYmUzYTQyLThjNDEtNDYwMi1iMTliLTUxYmQ0ODFlZmZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxODA5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGQzNDk0OWI1NGUyMjFhM2VhYmYyNzA1ZjMwMDg5YzAwYTg2NDI2MTllZDRmYzUzNDE0YTlkZmI2ZTA5ZTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-9PH5C6Z7p_dJapiIvSkgalb_PxzfyBAYB95lQsXsbM)
> 
> Windows 11 Pro 23H2 22631.3880 Windows Feature Experience Pack 1000.22700.1020.0
> 
> Thank you for your work Je
> 
> Edit : i have fix issue with update rootstore.sst via certUtils !!!

Hi je -sam, can you provide a tutorial on how you fixed the issue "update rootstore.sst vie certutils?

**Comment by prateekmedia** [comment] 2024-08-22 10:03
For anyone interested (including @marklesterb28) in knowing the fix, I have documented it in this github discussions:
https://github.com/ente-io/ente/discussions/2819

**Comment by DClem85** [comment] 2024-09-03 02:15
@prateekmedia can you please provide context here? discussion #2819 shows up as a blank entry and the issue is still persisting on recent builds.

**Comment by ua741** [comment] 2024-09-03 08:33
> @prateekmedia can you please provide context here? discussion #2819 shows up as a blank entry and the issue is still persisting on recent builds.

@DClem85 We have moved the guide to this location https://help.ente.io/auth/troubleshooting/windows-login

**Comment by gokulkgm** [comment] 2024-09-03 08:36
@ua741 It would be helpful if the app shows specific error and the troubleshooting link in case this error occurs.

**Comment by Marcbacca** [comment] 2024-09-26 05:32
Hi, any update on this? It's not working with Win 11 using 4.0.2. Worked fine in PopOS (flatpak), then I reinstalled Windows and cannot login at all, obviously an issue.
![Screenshot 2024-09-26 003015](https://github.com/user-attachments/assets/99d5b4d3-b022-49d9-8166-30d77375a8e8)
